### ISSUE TITLE
Непонятная ошибка

### ISSUE THREAD

**Issue by XRain777** [7even/vkontakte_api#72]
```
*...*gems/faraday_middleware-parse_oj-0.3.0/lib/faraday_middleware/parse_oj.rb:8:in `load': unexpected character at line 1, column 1 [parse.c:661] (Faraday::ParsingError)
        from *...*gems/faraday_middleware-parse_oj-0.3.0/lib/faraday_middleware/parse_oj.rb:8:in `block in <class:ParseOj>'
        from *...*gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:48:in `call'
        from *...*gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:48:in `parse'
        from *...*gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
        from *...*gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
        from *...*gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
        from *...*gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
        from *...*gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
        from *...*gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
        from *...*gems/vkontakte_api-1.4.3/lib/vkontakte_api/logger.rb:21:in `call'
        from *...*gems/faraday-0.9.2/lib/faraday/request/retry.rb:116:in `call'
        from *...*gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
        from *...*gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in `call'
        from *...*gems/faraday_middleware-0.9.1/lib/faraday_middleware/request/oauth2.rb:41:in `call'
        from *...*gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from *...*gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from *...*gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from *...*gems/vkontakte_api-1.4.3/lib/vkontakte_api/api.rb:18:in `call'
        from *...*gems/vkontakte_api-1.4.3/lib/vkontakte_api/method.rb:13:in `call'
        from *...*gems/vkontakte_api-1.4.3/lib/vkontakte_api/resolver.rb:20:in `call_method'
        from *...*gems/vkontakte_api-1.4.3/lib/vkontakte_api/namespace.rb:12:in `method_missing'
        from test.rb:7:in `<main>'
```

Вот такое вот выдаёт при попытке вызова любого метода, если передавать access_token. Причём это только с одной конкретной страницей ВКонтакте, с других всё работает нормально. В чём может быть проблема?

test.rb: 

```
require 'vkontakte_api'
token=File.readlines('tokens')[0].chomp
client=VkontakteApi::Client.new(token)
client.messages.get_long_poll_server
```

**Comment by 7even** [comment]
Похоже, VK отдает не JSON - возможно, какие-то неполадки на их стороне. Заодно я бы проверил, что в `token` лежит валидный токен.

**Comment by XRain777** [comment]
Видимо, действительно неполадки были на стороне ВКонтакте. Ошибка как появилась, так и пропала сама по себе.
